services:
  - type: web
    name: vectocloud-review
    runtime: python
    repo: https://github.com/DeVv-Prime/Review-Page
    plan: free
    region: oregon
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn review:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
